name: My workflow test
on: 
  issues:
    types: opened
  workflow_dispatch:

jobs:
  files:
    runs-on: ubuntu-latest
    steps:
      - name: filecreation
        run: |
          touch info.txt
          echo "Heipparalla" > info.txt
      - name: backup
        run: |
          mkdir backup
          cp info.txt backup/info.txt
      - name: contents
        run: |
          ls -al
          la -al backup
          cat info.txt
    

