name: Pushing to repo
on: workflow_dispatch
permissions: 
  contents: write

jobs:
  repo-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Create new repo file
        run: |
          echo "Uusi rivi" >> README.md
          git config --global user.name 'repenaattori'
          git config --global user.email 'reimarii@oamk.fi'
          git add README.md
          git commit -m 'Add row into readme'
          git push
          
