name: Variables
on: push
env:
  MY_NAME: Reima Riihimäki
  URL: ${{vars.MY_SERVER_URL}}
jobs:
  repo-test:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "URL on $URL"
          echo "Password on ${{secrets.MY_PW}}"
          echo "Trigger branch is ${{github.repository}}"
      - run: echo "My info is ${{github.event.head_commit.author.username}}"
